### ISSUE TITLE
Error in  Feature Extraction step

### ISSUE THREAD

**Issue by AtefehSamadi** [gaochangw/DeltaLSTM-CBTD#1]
Hi,
Running the code main.py got the error:

```                        
####################################################################################################
# Step 1: Feature Extraction                                                                       #
####################################################################################################
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "G:\DeltaLSTM-CBTD-main\DeltaLSTM-CBTD-main\main.py", line 65, in <module>
    feat_ext.main(args=args)
  File "G:\DeltaLSTM-CBTD-main\DeltaLSTM-CBTD-main\steps\feat_ext.py", line 30, in main
    extractor.extract(args)
  File "G:\DeltaLSTM-CBTD-main\DeltaLSTM-CBTD-main\modules\timit\feat_extractor.py", line 99, in extract
    dataset_train = get_dataset(X_train, y_train_39, y_train_48, y_train_61, args.phn)
  File "G:\DeltaLSTM-CBTD-main\DeltaLSTM-CBTD-main\modules\timit\feat_extractor.py", line 77, in get_dataset
    features = np.concatenate(x, axis=0).astype(np.float32)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
```

It seems that the description.csv and  "feat" file isn't created completely.
Could you please help me with this?
Thanks in advance

**Comment by gaochangw** [comment]
Hi Atefeh,

Could you check whether description.csv is empty? If so, you probably did not put the correct path to your TIMIT dataset folder. Check util.py. I put my TIMIT folder under /DATA.

Best,
Chang

**Comment by AtefehSamadi** [comment]
Thanks for your consideration.
my description.csv is just filled by just one row, containing:
```
group,speaker,utt,key,modality,path,label61,label48,label39,phn61,phn48,phn39
```
I have put my TIMIT folder (which you have presented) under C:\DATA either, but unfortunately I have got the same error.

**Comment by gaochangw** [comment]
Sorry the code is not supposed to run in Windows. I only ran the code in Ubuntu. Your description.csv is empty, which should contain the paths of all .wav files in the TIMIT dataset. I think you will have to modify the way the code generates the path to the TIMIT folder if you want to use it in Windows.

**Comment by AtefehSamadi** [comment]
Thank you very kindly.
Would it be possible for you to send me the trained model? Cause I need to use the trained model in MATLAB

**Comment by gaochangw** [comment]
Here's what I have now. The link is valid until the end of this week. For proper use of the model, I encourage you to run and understand the code anyway.
https://www.dropbox.com/s/78qtuiz3gxtqvcg/SD_0_L_2_IN_123_H_768_CLA_LSTM_FC_768_QA_1_AI_8_AF_8_QW_1_WI_1_WF_7_CBWD_0_SPRNN_0.94_SPFC_0.94_AAE_30_NAP_64.pt?dl=0

**Comment by AtefehSamadi** [comment]
I appreciate your help getting what I need for the project.
Your advice is invaluable. I will surely try again to run the code myself. It was really clear and understandable code. I am grateful to you for sharing your wisdom.
Best regards,
Atefeh

**Comment by AtefehSamadi** [comment]
Hi,
Regarding my problem in creating description.csv, I would like to ask if the TIMIT dataset on GitHub is complete? 
Cause according to the data_collector, it seems that the data folder should contains TRAIN and TEST folders either.  
Could you please help me where can I find these folders?

**Comment by gaochangw** [comment]
Hi,

You can easily find this website on google.
https://huggingface.co/datasets/timit_asr

**Comment by AtefehSamadi** [comment]
Thank you so much.
